<!-- Uniting Skin -->
<link href="http://hombre.blocksglobal.com/repos/life_assist/uniting-skin/css/uniting-skin.css" rel="stylesheet" type="text/css">

<!-- Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-126479821-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-126479821-3');
</script>
