<div id="edit_container">



	<!-- EDIT SECTION 01 -->
	<div class="edit_section">
		<div class="section_heading">
			<label for="section_01" class="h1"></label>
			<label for="section_01" class="section_toggle">show/hide</label>
		</div>
		<input type="checkbox" class="section_checkbox" name="section_01" id="section_01">
		<div class="section_content">
			

		</div>
	</div> <!-- .edit_section 01 -->



	<!-- EDIT SECTION 02 -->
	<div class="edit_section">
		<div class="section_heading">
			<label for="section_02" class="h1"></label>
			<label for="section_02" class="section_toggle">show/hide</label>
		</div>
		<input type="checkbox" class="section_checkbox" name="section_02" id="section_02">
		<div class="section_content">
			

		</div>
	</div> <!-- .edit_section 02 -->



	<!-- EDIT SECTION 03 -->
	<div class="edit_section">
		<div class="section_heading">
			<label for="section_03" class="h1"></label>
			<label for="section_03" class="section_toggle">show/hide</label>
		</div>
		<input type="checkbox" class="section_checkbox" name="section_03" id="section_03">
		<div class="section_content">
			

		</div>
	</div> <!-- .edit_section 03 -->



</div> <!-- #edit_container -->