<div class="search-box">
    <div class="max-width-wrap">

        <form action="#" class="form search-form">
            <input type="text" name="term" placeholder="search lifeAssist">
            <button type="submit" class="">
                <span class="btn-state-default">SEARCH</span>
                <img src="/templates/life_assist/img/site/icon_loader_blue.gif" height="16" width="16" class="btn-state-sending">
            </button>
        </form>
        <div class="search-result-list"></div> <!-- .search-result-list -->

    </div> <!-- .max-width-wrap -->
</div> <!-- .search-box -->